apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
          # - name: MONGO_INITDB_ROOT_USERNAME #can input the value directly but that usually is not the case;we need the values stored in a secret
          #   value: victor
          - name: MONGO_INITDB_ROOT_USERNAME #can input the value directly but that usually is not the case;we need the values stored in a secret
            valueFrom: 
              secretKeyRef:
                name: mongodb-secret
                key: USERNAME

          - name: MONGO_INITDB_ROOT_PASSWORD
            value: victor
          # - name: MONGO_INITDB_ROOT_PASSWORD #this is after having the values in a secret
          #   valueFrom: 
          #     secretKeyRef:
          #       name: mongodb-secret
          #       key: PASSWORD